project/files/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<id>.*)/hot/$', views.hotlink_file_download, name="file_hot"),
    url(r'^(?P<id>.*)/(?P<token>.*)/$', views.file_download, name="file_download"),
    url(r'^(?P<id>.*)/$', views.SharedFileDetails.as_view(), name="file"),
]

project/pages/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index")
]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from project.files.views import uploaded_file

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_resumable/', include('admin_resumable.urls')),
    url(r'^files/', include('project.files.urls', namespace="files")),
    url(r'^uploads/(?P<filename>.*)', uploaded_file, name="upload"),
    url(r'', include("project.pages.urls", namespace="pages"))
]


urlpatterns += staticfiles_urlpatterns()

project/files/models.py
from django.db import models
import uuid
from admin_resumable.fields import ModelAdminResumableFileField
from shortuuidfield import ShortUUIDField
from datetime import timedelta
from django.core.urlresolvers import reverse
import os.path
from django.conf import settings


class SharedFile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    short_id = ShortUUIDField()
    created = models.DateTimeField(auto_now_add=True)
    file = ModelAdminResumableFileField()
    hotlink = models.BooleanField(default=False)
    published = models.BooleanField(default=True)

    def __str__(self):
        return self.get_original_filename()

    def get_original_filename(self):
        return "_".join(self.file.name.split('_')[1:])

    def get_absolute_url(self):
        return reverse('files:file', args=(self.short_id,))

    def get_type_image(self):
        extension = self.get_original_filename().split('.')[-1]
        icon_file = os.path.join(settings.STATICFILES_DIRS[0], 'img', 'icons', "{0}.png".format(extension))
        filename = extension if os.path.exists(icon_file) else "_page"
        return os.path.join(settings.STATIC_URL, 'img', 'icons', "{0}.png".format(filename))


class FileToken(models.Model):
    valid_time = timedelta(minutes=5)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    token = ShortUUIDField()
    file = models.ForeignKey(SharedFile, null=False, blank=False, related_name="tokens")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Token for {0} created at {1}".format(self.file.file.name, self.created)

project/files/views.py
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404
from django.http import FileResponse as BaseFileResponse
from .models import SharedFile, FileToken
import mimetypes
from django.utils import timezone
from django.contrib.auth.decorators import login_required


mimetypes.init()


class SharedFileDetails(TemplateView):
    template_name = "file.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['file'] = get_object_or_404(SharedFile, short_id=kwargs['id'])
        context['token'] = FileToken.objects.create(file=context['file'])
        return context


def FileResponse(file):
    response = BaseFileResponse(file.file)
    response['Content-Type'] = mimetypes.guess_type(file.get_original_filename())[0]
    response['Content-Disposition'] = 'attachment; filename="{0}"'.format(file.get_original_filename())
    return response


def file_download(request, id, token):
    time_threshold = timezone.now() - FileToken.valid_time
    FileToken.objects.filter(created__lt=time_threshold)
    file = get_object_or_404(SharedFile, short_id=id, published=True)
    token = get_object_or_404(FileToken, token=token, file=file)
    token.delete()  # delete after used
    return FileResponse(file)


def hotlink_file_download(request, id):
    file = get_object_or_404(SharedFile, short_id=id, hotlink=True, published=True)
    return FileResponse(file)


@login_required
def uploaded_file(request, filename):
    file = get_object_or_404(SharedFile, file=request.get_full_path()[1:])  # strip preceding slash
    response = FileResponse(file)
    return response

project/pages/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

templates/base.html
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <title>{% block title %}{% endblock %} | StaticShare</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
  <script src="{% static 'js/jquery.js' %}"></script>
</head>
<body>
  <section id="section-wrapper">
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </section>
  <footer>
    <div class="container">
      <p>Powered by Static-Share</p>
    </div>
  </footer>
  <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

templates/file.html
{% extends 'base.html' %}

{% block title %}Download {{ file.get_original_filename }}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="thumbnail file">
        <img src="{{ file.get_type_image }}" />
        <div class="caption">
          <h3>{{ file.get_original_filename }}</h3>
          <h5>Created at: {{ file.created }}</h5>
        </div>
        {% if file.hotlink %}
          <a class="btn btn-primary btn-block btn-lg download-button" href="{% url 'files:file_download' file.short_id token.token %}">
            Download {{ file.get_original_filename }}
          </a>
          <p class="timer-message">This download link is only valid for <span class="timer" data-duration="{{ token.valid_time.seconds }}"></span>.</p>
        {% else %}
          <a class="btn btn-primary btn-block btn-lg download-button" href="{% url 'files:file_hot' file.short_id %}">
            Download {{ file.get_original_filename }}
          </a>
          <p>Hotlinking is enabled for this file.</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Homepage{% endblock %}

{% block content %}
  <h1>Index</h1>
{% endblock %}